import Head from "next/head";
import { Inter } from "next/font/google";
import { Children } from "@/types/global";

import styles from "./app.module.css";

const inter = Inter({ subsets: ["latin"] });

export const AppLayout = ({ children }: Children) => {
  return (
    <>
      <style jsx global>{`
        html {
          font-family: ${inter.style.fontFamily};
        }
      `}</style>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>{children}</main>
    </>
  );
};
